//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MotSysCfg.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MOTCFG_DLG                  101
#define IDD_MOTSYSCFG_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_AXIS_DLG                    129
#define IDD_MOTCTRLR_DLG                130
#define IDC_BTN_ABOUT                   1001
#define IDC_CHK_MOTCFG                  1002
#define IDC_CHK_BIGX                    1003
#define IDC_BTN_LOAD                    1003
#define IDC_CHK_BIGY                    1004
#define IDC_BTN_SAVE                    1004
#define IDC_CHK_Z                       1005
#define IDC_EDIT_BASE_ADDR1             1005
#define IDC_CHK_XSLOW                   1006
#define IDC_EDIT_BASE_ADDR2             1006
#define IDC_CHK_THETA                   1007
#define IDC_EDIT_BASE_AXISNUM           1007
#define IDC_EDIT_LOWGAIN                1007
#define IDC_CHK_LEVEL                   1008
#define IDC_EDIT_AXIS_NAME_BIGX         1008
#define IDC_EDIT_ORG1_ATT_X             1008
#define IDC_CHK_XFAST                   1009
#define IDC_EDIT_HCTLPORT_BIGX          1009
#define IDC_EDIT_ORG1_ATS_X             1009
#define IDC_CHK_Y                       1010
#define IDC_EDIT_HOMEPORT_BIGX          1010
#define IDC_EDIT_HIGHGAIN               1010
#define IDC_EDIT_ORG1_SPD_X             1010
#define IDC_EDIT_HOMEINTPORT_BIGX       1011
#define IDC_EDIT_ZERO                   1011
#define IDC_CHK_SERVO                   1011
#define IDC_EDIT_ORG2_ATT_X             1011
#define IDC_EDIT_HOMEBIT_BIGX           1012
#define IDC_EDIT_POLE                   1012
#define IDC_EDIT_ORG2_ATS_X             1012
#define IDC_EDIT_HOMEINTBIT_BIGX        1013
#define IDC_EDIT_SAMPLETIME             1013
#define IDC_EDIT_ORG2_SPD_X             1013
#define IDC_EDIT_STOPBIT_BIGX           1014
#define IDC_EDIT_PWMMAX                 1014
#define IDC_EDIT_ORG3_ATT_X             1014
#define IDC_EDIT_UNUSED_BIGX            1015
#define IDC_EDIT_PWMFILTER              1015
#define IDC_EDIT_ORG3_ATS_X             1015
#define IDC_EDIT_AXIS_NAME_BIGY         1016
#define IDC_EDIT_MODE                   1016
#define IDC_EDIT_ORG3_SPD_X             1016
#define IDC_EDIT_AXIS_NAME_Z            1017
#define IDC_EDIT_DISTINATION            1017
#define IDC_EDIT_HP_ATT_X               1017
#define IDC_EDIT_AXIS_NAME_XSLOW        1018
#define IDC_EDIT_MAX_VELOCITY           1018
#define IDC_EDIT_HP_ATS_X               1018
#define IDC_EDIT_AXIS_NAME_THETA        1019
#define IDC_EDIT_INTEG_VELOCITY         1019
#define IDC_EDIT_HP_BASE_X              1019
#define IDC_EDIT_AXIS_NAME_LEVEL        1020
#define IDC_EDIT_PROP_VELOCITY          1020
#define IDC_EDIT_ABS_ATT_X              1020
#define IDC_EDIT_AXIS_NAME_XFAST        1021
#define IDC_EDIT_ACCEL                  1021
#define IDC_EDIT_ABS_ATS_X              1021
#define IDC_EDIT_AXIS_NAME_Y            1022
#define IDC_EDIT_HCTL_STAT              1022
#define IDC_EDIT_INC_ATT_X              1022
#define IDC_EDIT_HCTLPORT_BIGY          1023
#define IDC_EDIT_UNUSED                 1023
#define IDC_EDIT_ORG1_ATT_Y             1023
#define IDC_EDIT_HCTLPORT_Z             1024
#define IDC_EDIT_MLIMIT                 1024
#define IDC_EDIT_INC_ATS_X              1024
#define IDC_EDIT_HCTLPORT_XSLOW         1025
#define IDC_EDIT_PLIMIT                 1025
#define IDC_EDIT_ORG1_ATS_Y             1025
#define IDC_EDIT_HCTLPORT_THETA         1026
#define IDC_EDIT_INVERT                 1026
#define IDC_EDIT_ORG1_SPD_Y             1026
#define IDC_EDIT_HCTLPORT_LEVEL         1027
#define IDC_EDIT_FWD_HOME               1027
#define IDC_EDIT_ORG2_ATT_Y             1027
#define IDC_EDIT_HCTLPORT_XFAST         1028
#define IDC_EDIT_HOME_VELOCITY          1028
#define IDC_EDIT_ORG2_ATS_Y             1028
#define IDC_EDIT_HCTLPORT_Y             1029
#define IDC_EDIT_HOME_ACCEL             1029
#define IDC_EDIT_ORG2_SPD_Y             1029
#define IDC_EDIT_HOMEPORT_BIGY          1030
#define IDC_EDIT_DEFMOTP                1030
#define IDC_EDIT_ORG3_ATT_Y             1030
#define IDC_EDIT_HOMEINTPORT_BIGY       1031
#define IDC_EDIT_ORG3_ATS_Y             1031
#define IDC_EDIT_HOMEBIT_BIGY           1032
#define IDC_EDIT_ORG3_SPD_Y             1032
#define IDC_EDIT_HOMEINTBIT_BIGY        1033
#define IDC_EDIT_HP_ATT_Y               1033
#define IDC_EDIT_STOPBIT_BIGY           1034
#define IDC_EDIT_HP_ATS_Y               1034
#define IDC_EDIT_UNUSED_BIGY            1035
#define IDC_EDIT_HP_BASE_Y              1035
#define IDC_EDIT_HOMEPORT_Z             1036
#define IDC_EDIT_ABS_ATT_Y              1036
#define IDC_EDIT_HOMEINTPORT_Z          1037
#define IDC_EDIT_ABS_ATS_Y              1037
#define IDC_EDIT_HOMEBIT_Z              1038
#define IDC_EDIT_INC_ATT_Y              1038
#define IDC_EDIT_HOMEINTBIT_Z           1039
#define IDC_EDIT_INC_ATS_Y              1039
#define IDC_EDIT_STOPBIT_Z              1040
#define IDC_EDIT_ORG1_ATT_Z             1040
#define IDC_EDIT_UNUSED_Z               1041
#define IDC_EDIT_ORG1_ATS_Z             1041
#define IDC_EDIT_HOMEPORT_XSLOW         1042
#define IDC_EDIT_ORG1_SPD_Z             1042
#define IDC_EDIT_HOMEINTPORT_XSLOW      1043
#define IDC_EDIT_ORG2_ATT_Z             1043
#define IDC_EDIT_HOMEBIT_XSLOW          1044
#define IDC_EDIT_ORG2_ATS_Z             1044
#define IDC_EDIT_HOMEINTBIT_XSLOW       1045
#define IDC_EDIT_ORG2_SPD_Z             1045
#define IDC_EDIT_STOPBIT_XSLOW          1046
#define IDC_EDIT_ORG3_ATT_Z             1046
#define IDC_EDIT_UNUSED_XSLOW           1047
#define IDC_EDIT_ORG3_ATS_Z             1047
#define IDC_EDIT_HOMEPORT_THETA         1048
#define IDC_EDIT_ORG3_SPD_Z             1048
#define IDC_EDIT_HOMEINTPORT_THETA      1049
#define IDC_EDIT_HP_ATT_Z               1049
#define IDC_EDIT_HOMEBIT_THETA          1050
#define IDC_EDIT_HP_ATS_Z               1050
#define IDC_EDIT_HOMEINTBIT_THETA       1051
#define IDC_EDIT_HP_BASE_Z              1051
#define IDC_EDIT_STOPBIT_THETA          1052
#define IDC_EDIT_ABS_ATT_Z              1052
#define IDC_EDIT_UNUSED_THETA           1053
#define IDC_EDIT_ABS_ATS_Z              1053
#define IDC_EDIT_HOMEPORT_LEVEL         1054
#define IDC_EDIT_INC_ATT_Z              1054
#define IDC_EDIT_HOMEINTPORT_LEVEL      1055
#define IDC_EDIT_INC_ATS_Z              1055
#define IDC_EDIT_HOMEBIT_LEVEL          1056
#define IDC_EDIT_ORG1_ATT_T             1056
#define IDC_EDIT_HOMEINTBIT_LEVEL       1057
#define IDC_EDIT_ORG1_ATS_T             1057
#define IDC_EDIT_STOPBIT_LEVEL          1058
#define IDC_EDIT_ORG1_SPD_T             1058
#define IDC_EDIT_UNUSED_LEVEL           1059
#define IDC_EDIT_ORG2_ATT_T             1059
#define IDC_EDIT_HOMEPORT_XFAST         1060
#define IDC_EDIT_ORG2_ATS_T             1060
#define IDC_EDIT_HOMEINTPORT_XFAST      1061
#define IDC_EDIT_ORG2_SPD_T             1061
#define IDC_EDIT_HOMEBIT_XFAST          1062
#define IDC_EDIT_ORG3_ATT_T             1062
#define IDC_EDIT_HOMEINTBIT_XFAST       1063
#define IDC_EDIT_ORG3_ATS_T             1063
#define IDC_EDIT_STOPBIT_XFAST          1064
#define IDC_EDIT_ORG3_SPD_T             1064
#define IDC_EDIT_UNUSED_XFAST           1065
#define IDC_EDIT_HP_ATT_T               1065
#define IDC_EDIT_HOMEPORT_Y             1066
#define IDC_EDIT_HP_ATS_T               1066
#define IDC_EDIT_HOMEINTPORT_Y          1067
#define IDC_EDIT_HP_BASE_T              1067
#define IDC_EDIT_HOMEBIT_Y              1068
#define IDC_EDIT_ABS_ATT_T              1068
#define IDC_EDIT_HOMEINTBIT_Y           1069
#define IDC_EDIT_ABS_ATS_T              1069
#define IDC_EDIT_STOPBIT_Y              1070
#define IDC_EDIT_INC_ATT_T              1070
#define IDC_EDIT_UNUSED_Y               1071
#define IDC_EDIT_INC_ATS_T              1071
#define IDC_EDIT_STOPPORT_BIGX          1072
#define IDC_EDIT_HP_SPD_X               1072
#define IDC_EDIT_STOPPORT_BIGY          1073
#define IDC_EDIT_HP_SPD_Y               1073
#define IDC_EDIT_STOPPORT_Z             1074
#define IDC_EDIT_HP_SPD_Z               1074
#define IDC_EDIT_STOPPORT_XSLOW         1075
#define IDC_EDIT_HP_SPD_T               1075
#define IDC_EDIT_STOPPORT_THETA         1076
#define IDC_EDIT_ABS_SPD_X              1076
#define IDC_EDIT_STOPPORT_LEVEL         1077
#define IDC_EDIT_ABS_SPD_Y              1077
#define IDC_EDIT_STOPPORT_XFAST         1078
#define IDC_EDIT_ABS_SPD_Z              1078
#define IDC_EDIT_STOPPORT_Y             1079
#define IDC_EDIT_ABS_SPD_T              1079
#define IDC_EDIT_INC_SPD_X              1080
#define IDC_EDIT_INC_SPD_Y              1081
#define IDC_EDIT_INC_SPD_Z              1082
#define IDC_EDIT_INC_SPD_T              1083
#define IDC_STATIC_LBL_X                1084
#define IDC_STATIC_LBL_Y                1085
#define IDC_STATIC_LBL_Z                1086
#define IDC_STATIC_LBL_T                1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
