; Chief ダイアログ表示制御
[ShowSW]
; 表示形式
;	0：非表示(デフォルト)
;	1：アイコン化
;	2：そのまま
Type=2
; 表示ディレイ(表示形式を行う待ち時間：[s])
;	デフォルト：5[s]
Delay=5

; DIO 無視スイッチ
;	0：入力を無視しません(デフォルト)
;	1：入力を無視します
[DioIgnoreSW]
; 入力無視スイッチ．「1」で無視します．
; ロボットアーム検出
RobotArm=1
; ピンダウン検出
PinDown=1
; エア圧力低下検出
AirPressureLow=0

; テスト(デバッグ)用
[ForTest]
; 「forTEST」ボタンの有効(≠0)/無効(＝0)
forTESTBtn=0
