;*****************************************
;*  demo di/o configuration data         *
;*****************************************
;[Dio]
;Driver No=Contec driver number
;Group No=Contec group number
;Port Num=Contec port num
[Dio]
Driver No=4
Group No=1
Port Num=16
