[LANGUAGE]
Language=Japanese
;Language=English

[RESULTDIR]
DefNanoSpecResult=c:\NanoSpec\Result
NanoSpecResult=C:\NanoSpec\RESULT

[STAGE CONFIG]
MachineOrgSensorLoc=2
OriginPosition=3
CoordinateDirection_X=1
CoordinateDirection_Y=2
