;*****************************************
;*  nextra configuration data            *
;*****************************************
;[System]
;Language= 0:Englisth,1:Japanese
;Type= 0:TypeA(SHARP), 1:TypeB(PKI) 2:TypeC 3:TypeD(Alignment None) 4:TypeE(T3100)
;Mode= 0:FA22_PLS, 1:FA22_Pro, 2:FA22_oP
;Vacuum Feedback= TRUE/FALSE
;Confirm Operator= TRUE/FALSE
;Show= 0:show, 1:minimize, 2:hide
;Robot Arm Interlock= TRUE/FALSE
;[Dio]
;Driver No=Contec driver number
;Group No=Contec group number
;Port Num=Contec port num
;[Sio]
;Axis 1 Port No=ADAX serial communication port number
;Axis 1 Baud Rate= 9600,19200, 38400...
;[Timeouts]
;Homing=mm(sec)
;Origin Return=mm(sec)
;Teach Location=mm(sec)
;Work Guide Open/Close=mm(sec)
;Vacuum On=mm(sec)
;Vacuum Off=mm(sec)
;Shutter Open=mm(sec)
;Shutter Close=mm(sec)
;[Delay]
;Work Guide Open=mm(sec)
;Work Guide Close=mm(sec)
;Vacuum Destruct=mm(sec)
;Servo On=mm(sec)
;[ADAX]
;H/W Simulation= 0:Hardware, 1:Simulation
;Resolution=ADAX servo resolution(pls/mm)
;T1=mm(sec)
;T2=mm(sec)
;T3=mm(sec)
;[Shutter]
;Cylinder= 2 or 3(num of solenoid valve)
;[Options]
;Shutter= TRUE/FALSE
;Air Float= TRUE/FALSE

[System]
Language=0
;Type=3
Type=4
Mode=2
Vacuum Feedback=TRUE
Confirm Operator=FALSE
Robot Arm Interlock=FALSE
Show=1
FirstValve=0

[Dio]
;Driver No=2
Driver No=4
Group No=1
Port Num=8

[Sio]
Axis 1 Port No=4
Axis 1 Baud Rate=19200
Axis 2 Port No=5
Axis 2 Baud Rate=19200

[Timeouts]
Homing=30000
Origin Return=30000
Teach Location=30000
Work Guide Open/Close=30000
Vacuum On=30000
Vacuum Off=30000
Shutter Open=10000
Shutter Close=10000

[Delay]
Work Guide Open=1000
Work Guide Close=2000
Vacuum Destruct=1000
Servo On=500

[ADAX]
H/W Simulation=0
Resolution=16384
T1=30
T2=1000
T3=15000

[Shutter]
Cylinder=3
Initial Close=FALSE

[Options]
Shutter=FALSE
Air Float=FALSE
Robo Cylinder=FALSE
[Robo Cylinder]
Initial Pos No=1
Servo On=30000
Homing=30000
Teach Position=30000

[Glass Exist]
Count=2
[Vacuum Pressure]
Count=1
