; 軸設定 -------------------------------------------------------------
[Axis]
; X/Y 入替え．0：入替えない，1：入替える
;	デフォルト =0
ChangeAxisEnable=0
; 軸使用指定	X/Y 軸は必ず使用なので，以外を指定します．
;	デフォルト値 =0
;EnableAxisX=1
;EnableAxisX=1
EnableAxisZ=0
EnableAxisT=0
; 移動方向反転
;	デフォルト値 =0
InvertedSenseX=1
InvertedSenseY=0
InvertedSenseZ=0
InvertedSenseT=0
; Y 軸の加速度切替範囲 [count]
;	移動距離が指定距離以内なら X 軸の加速パラメタを使う
;	デフォルト値 =80000
YAccelXRange=80000

; 最大速度制限設定 ---------------------------------------------------
[MaxSpeed]
; X 軸 [count/ms]
;	デフォルト値 =2000	範囲：10 ～
BigXMaxSpeed=8000
; Y 軸 [count/ms]
;	デフォルト値 =2000	範囲：10 ～
BigYMaxSpeed=8000
; T 軸	(Nano では未使用)
;	デフォルト値 =10	範囲： 5 ～ 10
ThetaMaxSpeed=10

; CONTEC DIO 設定 ----------------------------------------------------
[DIO]
; ドライバ No.
;	デフォルト値 =2
DrvNo=2
; グループ No.
;	デフォルト値 =1
GrpNo=2

; 現在値記憶 ---------------------------------------------------------
[CurrentPosition]
; 詳細不明．調査が必要です．現在位置記憶	(Nano では未使用)
;	デフォルト値 =0
Theta=0

; 表示設定 -----------------------------------------------------------
[Window]
; MotSys ダイアログの起動時の表示状態
;	0：表示
;	1：最小化
;	2：最小化＆非表示
;	デフォルト値 =2
AutoHide=1

; ログ設定 -----------------------------------------------------------
[Log]
; サーボコントローラとの通信ログ．0：しない，1：する
;	デフォルト値 =0
ComLog=0
