[SIMULATION]
;HWSimulation=TRUE

[CCDDATA]
SaveScanDataLog=FALSE

[HEADCOM]
CommNo=COM3
BaudRate=230400
Parity=N
ByteSize=8
StopBits=1
CcdDataTransferModeBinary=1

[STAGESIZE]
HWStageSimulation=TRUE
StageSizeX=206700
StageSizeY=207200
EdgeSizeX=500
EdgeSizeY=500
OriginOffsetX=106800
OriginOffsetY=100100

; 先行移動
[PreMove]
; 先行移動有無
;	0：無し(デフォルト)
;	1：有り
PreMoveSW=1
; 測定(AF)前のヘッド揺れ収束時間待ち設定
;	0-10000[ms]：10000[ms]以上の場合は 10000[ms] になります．
;		・シーケンス測定，リファレンス測定時のみ実施されます．
;		・先行移動の有無に関係無く実施されます．
WaitMeasTime=100
; 先行 AF 有無
;	0：無し(デフォルト)
;	1：有り
PreAFSW=0
; デバッグ用：解析(MEAS_Analysis())直前のディレイ[ms]
;tstdelay=0

[EQ Maintenance]
; メンテ SW オン検出時，サイクル停止するかどうかのスイッチ
;	(アラーム発報も含みます)
;	ただし，発報＆サイクル停止は，東朋メンテ SW がオフの場合のみ
;	=FALSE	しない
;	=TRUE	する
CycleStop=FALSE
; メンテ SW オンのとき，ドア開を検出するかどうか．
;	=FALSE	しない
;	=TRUE	する
DoorOpen=FALSE
; メンテ SW オンのとき，移動速度制限をするかどうか．
;	=FALSE	しない
;	=TRUE	する
SpeedDown=FALSE
; 装置電源オフ機能の有効/無効．
;	=FALSE	無効
;	=TRUE	有効
EQPowerOff=FALSE
; ドア開時，測定ポーズするかどうか．
;	=FALSE	しない
;	=TRUE	する
DoorOpenPause=TRUE

[StageCoord]
; 座標単位を設定してください
;	数値単位は [um] ですので，
;		座標値 100 を 100[um] としたい場合は，1
;		座標値 100 を 10[um] としたい場合は，0.1
;	となります．
;	また，符号により移動方向が反転します．
Xunit=-1
Yunit=-1
; 標準最高速度を指定します．
;	速度指定の無い動作指令で使われます．
;	単位は Xunit/Yunit で指定した単位になりますので，[単位/ms] です．
Xspeed=400
Yspeed=400

[DioIgnoreSW]
; ピンとシャッタの同時動作設定
;	＝1：ピン＆シャッタ同時動作可能
;	≠1：ピン＆シャッタ同時動作不可能
;		P603：バキューム ON 指示要求
;		P604：バキューム OFF 指示要求
;		P605：アライメント LOAD 指示要求
;		P606：アライメント UNLOAD 指示要求
;		P607：PINUP 指示要求
;		P608：PINDOWN 指示要求
;	　　と
;		P609：シャッタ OPEN 指示要求
;		P610：シャッタ CLOSE 指示要求
;	　　間のインタロックを解除し，同時動作出来るようにします．
PinShutterILInvalid=1

[SubConPwr]
; 起動時の初期化時のサブコンリセット機能
; オフ時間[s]
;	0：無し(デフォルト)
;		この時間の間，サブコン電源をオフします．
OffTime=0
; オン後起動待ち時間[s]
;	デフォルト：2
;		この時間経過してから初期化を続行します．
WaitAfterOn=2

[ModelType]
;モデルタイプ
TYPE=3100
;TYPE=6500

[OVideo]
;ビデオ表示　0:無効  1:有効  1以外:0と同じ（無効）
Enable=0
;VideoFormatSize=RGB32 (640x480)
;VideoFormatSize=Y800 (640x480)
;VideoFormatSize=RGB32 (1024x768)
;VideoFormatSize=Y800 (1024x768)
VideoFormatSize=RGB32 (1280x960)
;VideoFormatSize=Y800 (1280x960)
