//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MOTTSK.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDC_ALIGN_ANGLE                 104
#define IDC_ALIGN_MODE                  105
#define IDD_MOVE_SUBSTRATE              106
#define IDC_SOURCE                      108
#define IDC_TARGET_LOC                  109
#define IDC_SLOT                        110
#define IDD_ALIGN_MODE                  111
#define IDD_RECOVER_SUBSTRATE           112
#define ID_ACTION_INIT                  32768
#define ID_ACTION_ALIGN_OPTIONS         32769
#define ID_FILE_INIT                    32771
#define ID_ACTION_MOVE                  32772
#define ID_HOME_AXIS                    32772
#define ID_QUERY_CONFIG                 32773
#define ID_ACTION_CLEAR_INSTR           32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         101
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
