//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MotSysG.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MOTSYS_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDC_BTN_ABOUT                   1000
#define IDC_BTN_HIDE                    1001
#define IDC_BTN_Test                    1002
#define IDC_BTN_SERVO_OFF               1002
#define IDC_STATIC_STATUS               1003
#define IDC_STATIC_PROCPRI              1004
#define IDC_STATIC_PROCPRI2             1005
#define IDC_STATIC_COMSTAT              1006
#define IDC_STATIC_AXIS_X               1007
#define IDC_STATIC_AXIS_YM              1008
#define IDC_STATIC_AXIS_YS              1009
#define IDC_STATIC_AXIS_Z               1010
#define IDC_STATIC_AXIS_T               1011
#define IDC_STATIC_SEND                 1012
#define IDC_STATIC_RECV                 1013
#define IDC_STATIC_MODE_X               1014
#define IDC_BTN_COMLOGENA               1014
#define IDC_STATIC_MODE_YM              1015
#define IDC_BTN_COMLOGCLR               1015
#define IDC_STATIC_MODE_YS              1016
#define IDC_STATIC_MODE_Z               1017
#define IDC_STATIC_MODE_T               1018
#define IDC_STATIC_POS_X                1019
#define IDC_STATIC_POS_YM               1020
#define IDC_STATIC_POS_YS               1021
#define IDC_STATIC_POS_Z                1022
#define IDC_STATIC_POS_T                1023
#define IDC_BTN_ORGtest                 1024
#define IDC_BTN_ORGtestX                1024
#define IDC_BTN_Test2                   1025
#define IDC_BTN_SERVO_ON                1025
#define IDC_BTN_ORGtestY                1026
#define IDC_BTN_ORGtestZ                1027
#define IDC_BTN_ORGtestT                1028
#define IDC_BTN_ABStestX                1029
#define IDC_BTN_ABStestY                1030
#define IDC_BTN_ABStestZ                1031
#define IDC_BTN_ABStestT                1032
#define IDC_BTN_INCtestX                1033
#define IDC_BTN_INCtestY                1034
#define IDC_BTN_INCtestZ                1035
#define IDC_BTN_INCtestT                1036
#define IDC_BTN_HPtestX                 1037
#define IDC_BTN_HPtestY                 1038
#define IDC_BTN_HPtestZ                 1039
#define IDC_BTN_HPtestT                 1040
#define IDC_BTN_ABStestX2               1041
#define IDC_BTN_ABStestX3               1042
#define IDC_BTN_INCtestX2               1042
#define IDC_BTN_ABStestY2               1043
#define IDC_BTN_INCtestY2               1044
#define IDC_BTN_INCtestZ2               1045
#define IDC_BTN_INCtestT2               1046
#define IDC_BTN_ABStestZ2               1047
#define IDC_BTN_ABStestT2               1048
#define IDC_BTN_SERVO_PARAM             1049
#define IDC_STATIC_DESTPOS_X            1050
#define IDC_STATIC_DESTPOS_Y            1051
#define IDC_STATIC_DESTPOS_Z            1052
#define IDC_STATIC_DESTPOS_T            1053
#define IDC_STATIC_PTN_X                1054
#define IDC_STATIC_PTN_Y                1055
#define IDC_STATIC_PTN_Z                1056
#define IDC_STATIC_PTN_T                1057
#define IDC_STATIC_SOFTHP_X             1058
#define IDC_STATIC_SOFTHP_Y             1059
#define IDC_STATIC_SOFTHP_Z             1060
#define IDC_STATIC_SOFTHP_T             1061
#define IDC_STATIC_SPEED_X              1062
#define IDC_STATIC_SPEED_Y              1063
#define IDC_STATIC_SPEED_Z              1064
#define IDC_STATIC_SPEED_T              1065
#define IDC_STATIC_PRC_X                1066
#define IDC_STATIC_PRC_Y                1067
#define IDC_STATIC_PRC_Z                1068
#define IDC_STATIC_PRC_T                1069
#define IDC_STATIC_DPOSR_X              1070
#define IDC_STATIC_DPOSR_YM             1071
#define IDC_STATIC_DPOSR_YS             1072
#define IDC_STATIC_DPOSR_Z              1073
#define IDC_STATIC_DPOSR_T              1074
#define IDC_STATIC_DPOSPP_X             1075
#define IDC_STATIC_DPOSPM_X             1076
#define IDC_BTN_DPOSP_CLR_X             1077
#define IDC_BTN_DPOSP_CLR_YM            1078
#define IDC_BTN_DPOSP_CLR_YS            1079
#define IDC_BTN_DPOSP_CLR_Z             1080
#define IDC_BTN_DPOSP_CLR_T             1081
#define IDC_STATIC_DPOSPP_YM            1082
#define IDC_STATIC_DPOSPP_YS            1083
#define IDC_STATIC_DPOSPP_Z             1084
#define IDC_STATIC_DPOSPP_T             1085
#define IDC_STATIC_DPOSPM_YM            1086
#define IDC_STATIC_DPOSPM_YS            1087
#define IDC_STATIC_DPOSPM_Z             1088
#define IDC_STATIC_DPOSPM_T             1089
#define IDC_STATIC_DI                   1090
#define IDC_STATIC_DO                   1091
#define IDC_STATIC_DRVNO                1092
#define IDC_STATIC_GRPNO                1093
#define IDC_STATIC_LBL_STS_X            1094
#define IDC_STATIC_LBL_STS_YM           1095
#define IDC_STATIC_LBL_STS_YS           1096
#define IDC_STATIC_LBL_STS_Z            1097
#define IDC_STATIC_LBL_STS_T            1098
#define IDC_STATIC_LBL_PTN_X            1099
#define IDC_STATIC_LBL_PTN_Y            1100
#define IDC_STATIC_LBL_PTN_Z            1101
#define IDC_STATIC_LBL_PTN_T            1102
#define IDC_STATIC_LBL_POS_X            1103
#define IDC_STATIC_LBL_POS_YM           1104
#define IDC_STATIC_LBL_POS_YS           1105
#define IDC_STATIC_LBL_POS_Z            1106
#define IDC_STATIC_LBL_POS_T            1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
