#pragma once

/////////////////////////////////////////////////////////////////////////////
// Window Message
#define WM_TITLE									(WM_APP + 0x0800)
#define WM_SET_PROGRESS								(WM_TITLE + 0x00)
#define WM_SET_MESSAGE2								(WM_TITLE + 0x01)

/////////////////////////////////////////////////////////////////////////////
// IDS
#define TITLE_MSG2_LOAD_DATA						(101)
#define TITLE_MSG2_INIT_MEAS_HEAD					(102)
#define TITLE_MSG2_INIT_ALIGNMENT					(103)
#define TITLE_MSG2_INIT_STAGE						(104)
#define TITLE_MSG2_INIT_TURRET						(105)
#define TITLE_MSG2_INIT_MEAS_HEAD_SR				(201)
#define TITLE_MSG2_INIT_MEAS_HEAD_SE				(202)
#define TITLE_MSG2_INIT_MEAS_HEAD_RS				(203)
#define TITLE_MSG2_INIT_MEAS_HEAD_CTA				(204)
#define TITLE_MSG2_INIT_MEAS_HEAD_STRESS			(205)
