386_OBJECTS= \
    $(_OBJ_DIR)\i386\i8255.res \
    $(_OBJ_DIR)\i386\i8255.obj

PASS0_386_OBJECTS=

IA64_OBJECTS= \
    $(_OBJ_DIR)\ia64\i8255.res \
    $(_OBJ_DIR)\ia64\i8255.obj

PASS0_IA64_OBJECTS=

AMD64_OBJECTS= \
    $(_OBJ_DIR)\amd64\i8255.res \
    $(_OBJ_DIR)\amd64\i8255.obj

PASS0_AMD64_OBJECTS=

ARM_OBJECTS= \
    $(_OBJ_DIR)\arm\i8255.res \
    $(_OBJ_DIR)\arm\i8255.obj

PASS0_ARM_OBJECTS=

